### ISSUE TITLE
'Reader' Type Error

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#12]
`serialNumber` is of type string but `readers[0].serialNumber` returns a number and the `simulated` property is required so you're forced to specify it in `terminal.discoverReaders` AND `terminal.connectReader`.

```typescript
terminal.discoverReaders({
        simulated: false,
        deviceType: DeviceType.Chipper2X,
        discoveryMethod: DiscoveryMethod.BluetoothProximity
      })
      .subscribe(async readers => {
        if (readers.length) {
          console.log(readers);
          const connectedReader = await terminal.connectReader({ 
            serialNumber: readers[0].serialNumber.toString(),
            simulated: false
          });
          console.log(connectedReader);
        }
      })
```

**Comment by nprail** [comment]
@kyleabens Can you paste the output of `console.log(typeof readers[0].serialNumber);`? The `serialNumber` should never be of type `number` since it is not even a number (e.g. `CHB20SIMULATOR1`). It's also a string in Objective-C. 

![image](https://user-images.githubusercontent.com/10778661/83907534-926cdc80-a733-11ea-8503-0e72714697e2.png)

**Comment by kyleabens** [comment]
@nprail Sorry that's weird I swear I was getting a type error but I must have misread it. This is correct.  Also I'm trying to install the latest changes with `npm install https://github.com/eventOneHQ/capacitor-stripe-terminal.git`but after doing so it's unable to find the capacitor-stripe-terminal module.  I don't know npm that well so I'm not sure why this is happening or how I should go about implementing some of the latest commits you just made.  Let me know what I can do.

**Comment by nprail** [comment]
No problem! I'm going to re-open this for the `simulated` property being required because it isn't required. It defaults to true. 

Installing from npm, unfortunately, won't work because there is no built TypeScript in git. I'll be releasing a new version shortly.

**Comment by nprail** [comment]
Actually, you should just be able to pass the full `reader` object back into `connectReader` like so. Then you don't have to worry about what properties need to be passed to it. 
```typescript
terminal.discoverReaders({
  simulated: false,
  deviceType: DeviceType.Chipper2X,
  discoveryMethod: DiscoveryMethod.BluetoothProximity
})
  .subscribe(async readers => {
    if (readers.length) {
      const connectedReader = await terminal.connectReader(readers[0]);
      console.log(connectedReader);
    }
  })
```

**Comment by kyleabens** [comment]
Perfect thank you!

**Comment by kyleabens** [comment]
I'll close this and wait to test out the new version when it's released
