### ISSUE TITLE
Android Studio Error

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#18]
I know this plugin is only for iOS currently but when running `npx cap copy` after installing capacitor-stripe-terminal it copies it over to the Android platform as well.  Is there anyway to then remove it from Android?  When I go to generate an APK of my app in Android studio I get the following error:

`Package 'io.event1.capacitor-stripe-terminal.capacitorstripeterminal' from AndroidManifest.xml is not a valid Java package name as 'capacitor-stripe-terminal' is not a valid Java identifier.
`

I support both iOS and Android and build production versions all the time so I would hate to have to uninstall capacitor-stripe-terminal every time I need to build for Android.

**Comment by nprail** [comment]
I believe removing lines 44-46 of the `package.json` should signal to Capacitor that the plugin is iOS only. But I am not positive. Could you try doing that by editing the `package.json` in your `node_modules` folder? If that works, I'll make the change and release a new version. 

https://github.com/eventOneHQ/capacitor-stripe-terminal/blob/54b623d5a5146ff528a17d8464b2cf53d6593d8f/package.json#L44-L46

**Comment by kyleabens** [comment]
That seems to have done the trick, thanks!
