### ISSUE TITLE
Rejected by App Store for not providing Bluetooth Low Energy functionality

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#20]
Below is is the rejected response from Apple after submitting my app for review with the capacitor-stripe-terminal plugin.  Any idea what could be going on here?

**Guideline 2.5.4 - Performance - Software Requirements**

Your app declares support for bluetooth-central in the UIBackgroundModes key in your Info.plist but does not provide Bluetooth Low Energy functionality. The Bluetooth Background modes are for apps that communicate to other devices using Bluetooth Low Energy and the Core Bluetooth framework.

Next Steps

To resolve this issue, please revise your app to add support for Bluetooth Low Energy communication through Core Bluetooth in your app or remove the bluetooth- values from the UIBackgroundModes key.

Resources

For more information on Core Bluetooth, please review the Core Bluetooth Framework Reference.

**Comment by kyleabens** [comment]
It might be because my app requires the Stripe integration to access the plugin and the reviewer does not have access to that integration.

**Comment by nprail** [comment]
Hmm, this might be more of an issue to bring up on Stripe's [iOS SDK repo](https://github.com/stripe/stripe-terminal-ios/issues). 

What does your apps Terminal flow/use-case look like?

**Comment by kyleabens** [comment]
Once an account is integrated with Stripe and they go to create a payment in my app and select the card reader payment method it begins to scan for card readers and requests Bluetooth permission if its the first time or bluetooth is not enabled.  Then it lists all the discovered readers and the user can connect to anyone of them and process a payment.

**Comment by nprail** [comment]
@kyleabens Yeah, you may just have to explain that flow to Apple so that they know how to test. Their reviews are sometimes shockingly detailed.

**Comment by nprail** [comment]
@kyleabens Any updates on this? Did Apple approve the re-submission?

**Comment by kyleabens** [comment]
They required a video demonstrating the integration between the app and card reader.  After creating that and including it in the notes section of the submission, it was approved 👍
