### ISSUE TITLE
Property 'getPermissions' does not exist on type 'typeof StripeTerminalPlugin'

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#26]
**Describe the bug**
The getPermissions method for Android on StripeTerminalPlugin throws a type error.

**To Reproduce**
import { StripeTerminalPlugin } from 'capacitor-stripe-terminal';
StripeTerminalPlugin.getPermissions();

**Expected behavior**
It should recognize the getPermissions method.

**Screenshots**
<img width="926" alt="Screen Shot 2020-09-03 at 2 15 33 PM" src="https://user-images.githubusercontent.com/25699262/92151969-f1ec8e00-edef-11ea-84e0-d62521fa05f3.png">

**Comment by nprail** [comment]
@kyleabens I assume that you did, but just to be sure, did you upgrade to beta.6?

**Comment by kyleabens** [comment]
@nprail Yes sorry I was just coming back here to add that this is with beta.6

**Comment by kyleabens** [comment]
@nprail I just refreshed by IDE and that fixed it.

**Comment by nprail** [comment]
@kyleabens 👍 Was just going to ask if you had tried building it yet. I've seen VS Code do that sort of thing before...

**Comment by kyleabens** [comment]
@nprail yea it's annoying, I'll try to remember to do that before submitting an issue next time.
