### ISSUE TITLE
Feature request: Discover both Smart and Bluetooth card readers

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#34]
**Is your feature request related to a problem? Please describe.**
Right now you can only discover one type of card reader.

**Describe the solution you'd like**
The ability to discover both Verifone P400 and BBPOS Chippers 2 BT card readers.

**Describe alternatives you've considered**
I have tried the following using combineLatest
```

    const readers$ = [];

    readers$.push(this.callableService.stripeTerminalPlugin.discoverReaders({
      simulated: false,
      deviceType: DeviceType.VerifoneP400,
      discoveryMethod: DiscoveryMethod.Internet,
      locationId: this.account.integrations.stripe.locationId
    }));

    if (this.platform.is('capacitor')) {
      readers$.push(this.callableService.stripeTerminalPlugin.discoverReaders({
        simulated: false,
        deviceType: DeviceType.Chipper2X,
        discoveryMethod: DiscoveryMethod.BluetoothProximity,
      }));
    }

    combineLatest(readers$).subscribe((readers: any) => console.log(readers)

```

Unfortunately it didn't like that I was creating 2 instances of discoverReaders and through an error.

**Comment by nprail** [comment]
This could maybe be achieved by allowing the creation of a native instance and a JS instance of Terminal. That would take a significant amount of refactoring, I think. 

What is your use-case here? Do you just want to make it easier to connect to a reader by scanning for both types? What is the use case of having both types of readers deployed in one place?

**Comment by kyleabens** [comment]
I originally was achieving it like that before you added support for the JS SDK.  Now to simplify things I'm only utilizing this plugin.

My users are small businesses and a good amount of them have purchased the Verifone P400. They use our app on a tablet or smart phone to send the payment to the card reader.  For the users that have a Verifone P400 this card reader will no longer be discovered since I can only fetch one type of card reader at a time.  For devices running capacitor I have the app fetch BBPOS Chipper 2X BT readers via Bluetooth and if not using capacitor (browser) it queries Verifone P400 that are registered to the location of the account.  This is why it becomes an issue since I can no longer discover both types of readers.

**Comment by corysmc** [comment]
We had this same request for Table Needs. The issue is that sometimes the partner doesn't know what kind of reader they have. So it would be nice to use the api to discovery ANY readers - and then display them in a list for the customer to select.

**Comment by kyleabens** [comment]
@nprail any update on this one?

**Comment by nprail** [comment]
@kyleabens I actually just started to work on this today! It is a pretty significant and complex refactor, though, so it may take a while.

**Comment by nprail** [comment]
This behavior will be opt-in. I am implementing it via a new `DiscoveryMethod` which will search with `BluetoothScan` in the native SDK and `Internet` in the JS SDK. If you choose an `Internet` reader, the entire plugin will switch to the JS SDK instance. Otherwise, it will use the native SDK instance.

I'm currently calling the new discovery method `Both`. More clear name ideas would be appreciated :)

**Comment by nprail** [comment]
Initial work has been completed! It should be fully functional but there's a few edge cases that need to be resolved still.
