### ISSUE TITLE
The 'Pods-App' target has transitive dependencies that include statically linked binaries

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#69]
**Describe the bug**
I upgraded to v2.0.0-beta.2 and ran npx cap sync it fails for iOS and logs "The 'Pods-App' target has transitive dependencies that include statically linked binaries" and points to ios/App/Pods/StripeTerminal/StripeTerminal.xcframework

**To Reproduce**

1. npm install capacitor-stripe-terminal@v2.0.0-beta.2
2. npx cap sync

**Expected behavior**
For npx cap sync to succeed with v2.0.0-beta.2

**Screenshots**
<img width="987" alt="Screen Shot 2021-09-21 at 6 07 31 PM" src="https://user-images.githubusercontent.com/25699262/134255278-4a6f1e00-061a-410b-b4ac-3fb2325dcc43.png">

**Desktop (please complete the following information):**

- OS: macOS Big Sur v11.2.1
- Browser: Brave
- Version: 1.29.77

**Comment by nprail** [comment]
What is your CocoaPods version? Looks like you need CocoaPods 1.4.0 or greater. 

See CocoaPods/CocoaPods#7234

**Comment by kyleabens** [comment]
@nprail 1.8.4

**Comment by kyleabens** [comment]
@nprail I downgraded capacitor-stripe-terminal to v2.0.0-beta.1 and npx cap sync ran successfully so maybe it has something to do with Stripe Terminal v2?

**Comment by kyleabens** [comment]
@nprail I installed v2.0.0-beta.2 again and tried running  `pod cache clean` and `pod repo update` and then `npx cap sync` and still the same issue.

<img width="947" alt="Screen Shot 2021-09-22 at 12 33 30 PM" src="https://user-images.githubusercontent.com/25699262/134384919-89440080-a876-4b44-84f3-4f42a356bf70.png">
.

**Comment by nprail** [comment]
I vaguely remember running into this issue as well but I don't remember what I did to resolve it. Maybe try upgrading to the latest CocoaPods version? I am on 1.10 which seems to work.

**Comment by kyleabens** [comment]
upgraded CocoaPods to 1.11 and that seemed to do the trick, thanks!

**Comment by KBRR11** [comment]
I have CocoaPods 1.11.2 and i get this issue:
```
capacitor sync ios
[capacitor] ✔ Copying web assets from www to ios/App/App/public in 1.31s
[capacitor] ✔ Creating capacitor.config.json in ios/App/App in 946.80μp
[capacitor] [info] Found 10 Cordova plugins for ios:
[capacitor]        cordova-plugin-apprate@1.7.2
[capacitor]        cordova-plugin-dialogs@2.0.2
[capacitor]        cordova-plugin-globalization@1.11.0
[capacitor]        cordova-plugin-inappbrowser@4.1.0
[capacitor]        cordova-plugin-nativestorage@2.3.2
[capacitor]        cordova-plugin-x-socialsharing@5.6.8
[capacitor]        cordova-sqlite-storage@5.1.0
[capacitor]        cordova-uxcam@3.4.3
[capacitor]        es6-promise-plugin@4.2.2
[capacitor]        onesignal-cordova-plugin@2.11.4
[capacitor] ✔ copy ios in 1.42s
[capacitor] ✔ Updating iOS plugins in 36.93ms
[capacitor] [info] Found 9 Capacitor plugins for ios:
[capacitor]        @capacitor-community/apple-sign-in@1.0.1
[capacitor]        @capacitor-community/facebook-login@3.1.1
[capacitor]        @capacitor-community/firebase-analytics@1.0.0
[capacitor]        @capacitor/app@1.0.3
[capacitor]        @capacitor/device@1.0.3
[capacitor]        @capacitor/geolocation@1.1.0
[capacitor]        @capacitor/keyboard@1.0.3
[capacitor]        @codetrix-studio/capacitor-google-auth@3.0.2
[capacitor]        appsflyer-capacitor-plugin@6.4.0
[capacitor] [info] Found 10 Cordova plugins for ios:
[capacitor]        cordova-plugin-apprate@1.7.2
[capacitor]        cordova-plugin-dialogs@2.0.2
[capacitor]        cordova-plugin-globalization@1.11.0
[capacitor]        cordova-plugin-inappbrowser@4.1.0
[capacitor]        cordova-plugin-nativestorage@2.3.2
[capacitor]        cordova-plugin-x-socialsharing@5.6.8
[capacitor]        cordova-sqlite-storage@5.1.0
[capacitor]        cordova-uxcam@3.4.3
[capacitor]        es6-promise-plugin@4.2.2
[capacitor]        onesignal-cordova-plugin@2.11.4
[capacitor] ✖ Updating iOS native dependencies with pod install - failed!
[capacitor] ✖ update ios - failed!
[capacitor] [error] Analyzing dependencies
[capacitor]         AppsflyerCapacitorPlugin: Using AppsFlyerFramework/Strict mode
[capacitor]         Downloading dependencies
[capacitor]         Installing CordovaPlugins (3.3.2)
[capacitor]         Installing CordovaPluginsResources (0.0.105)
[capacitor]         Installing OneSignal (2.16.5)
[capacitor]         [!] The 'Pods-App' target has transitive dependencies that include statically linked binaries: (/Users/mac/Desktop/Front_App/ios/App/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework)
[capacitor]         
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor sync ios exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more
        information.
```

before I had no problems with doing npx or ionic capacitor sync, but my Mac had problems and I reset it, I don't know if the Cocoapods version has something to do or something like that

**Comment by nprail** [comment]
@KBRR11 It looks like your issue is with the OneSignal plugin, not `capacitor-stripe-terminal`. I would recommend creating an issue on their repository :)

**Comment by daisito** [comment]
Hi any news about theme , i have same problem
