### ISSUE TITLE
Add support for BBPOS Chipper 2X BT updates

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#72]
**Is your feature request related to a problem? Please describe.**
Yes, Stripe sent out an email blast making it clear that all BBPOS Chippers must download the latest firmware update by 12/31 to continue using the card reader.

**Describe the solution you'd like**
https://stripe.com/docs/terminal/readers/bbpos-chipper2xbt#required-updates

**Describe alternatives you've considered**
None

**Comment by kyleabens** [comment]
@nprail Is there a way to simulate an update to see if what I implemented works?

**Comment by nprail** [comment]
Yes, in v2 you can use the `setSimulatorConfiguration` method which is documented here:

https://oss.eventone.page/capacitor-stripe-terminal/classes/StripeTerminalPlugin.html#setSimulatorConfiguration
