### ISSUE TITLE
is BBPOS WisePOS E device supported?

### ISSUE THREAD

**Issue by indraraj26** [eventOneHQ/capacitor-stripe-terminal#77]
Ref: https://stripe.com/docs/terminal/payments/setup-reader/bbpos-wisepos-e

I have checked the interface i can only see two device 

``
Chipper2X = 0,
VerifoneP400 = 1
```

**Comment by nprail** [comment]
@indraraj26 The v2 beta supports the BBPOS WisePOS E! You can install it with the following:

```
npm install capacitor-stripe-terminal@beta
```

**Comment by indraraj26** [comment]
Hi @nprail , any example app branch for beta 

Thank you

**Comment by nprail** [comment]
@indraraj26 As of Stripe Terminal v2, all readers now have to be tied to a Stripe Location. You can find documentation explaining that here:
https://stripe.com/docs/terminal/fleet/locations

Unfortunately, I haven't had time to update the example branch yet for v2. 

`didRequestReaderDisplayMessage` and `didRequestReaderInput` should be subscribed to right before `collectPaymentMethod` and then unsubscribe right after.
