### ISSUE TITLE
[beta] getPaymentStatus event is missing

### ISSUE THREAD

**Issue by indraraj26** [eventOneHQ/capacitor-stripe-terminal#80]
**Describe the bug**
This will be useful event to know whether reader is ready for payment.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Docs: https://stripe.com/docs/terminal/references/api/js-sdk#get-payment-status

**Comment by nprail** [comment]
A `getPaymentStatus` method has been added in 2.1.0-beta.1!
