### ISSUE TITLE
Can not discover the reader Wisepad 3 BT

### ISSUE THREAD

**Issue by iborschca** [eventOneHQ/capacitor-stripe-terminal#84]
I am using iOS to discover devices.
BT permissions are allowed.
Simulator works perfect but not a real terminal.
The terminal is turned on in the discovery mode (BT icon is blinking).
Log from the App:
⚡️  To Native ->  App addListener 100936921
⚡️  To Native ->  StripeTerminal addListener 100936922
⚡️  To Native ->  StripeTerminal addListener 100936923
⚡️  To Native ->  StripeTerminal initialize 100936924
⚡️  TO JS {}
⚡️  TO JS undefined
⚡️  To Native ->  StripeTerminal setConnectionToken 100936925
⚡️  TO JS undefined
⚡️  [log] - Debug: Start discovering readers
⚡️  To Native ->  StripeTerminal addListener 100936926
⚡️  To Native ->  StripeTerminal discoverReaders 100936927

**Comment by iborschca** [comment]
Can provide you with all logs, details, help that I can to help you to solve the problem.

**Comment by nprail** [comment]
@iborschca Unfortunately, I don't have a Wisepad so I can't debug this myself. 

A few questions:
1. What `capacitor-stripe-terminal` version are you using?
2. Are you holding the Wisepad fairly close to the device you are trying to connect with?
3. What does your discovery code look like?
4. Have you successfully connected to any other Bluetooth readers?

**Comment by iborschca** [comment]
Hi.
1. v2
2. yes it is 10 cm far from the iPad
3. https://github.com/iborschca/i-borsch-new/blob/master/src/components/Menu.tsx#L76
4. No. This reader is the only one I have.
![image](https://user-images.githubusercontent.com/97372700/150855638-720446d2-67d3-4815-9a6a-9d1a39109da5.png)

**Comment by iborschca** [comment]
I found a fix! 
I replaced discoveryMethod in config for Terminal.shared.discoverReaders() with .bluetoothScan value and I managed to connect to the reader.
Was before:
![image](https://user-images.githubusercontent.com/97372700/150912750-14e0ab67-b889-4e6e-b400-b856aac50864.png)
Now:
![image](https://user-images.githubusercontent.com/97372700/150912780-8e2c54f3-c118-4719-ac0a-64f5d563a316.png)
According to [documentation](https://stripe.com/docs/terminal/payments/connect-reader)
![image](https://user-images.githubusercontent.com/97372700/150912842-b4427869-756d-485a-bddf-16678986afd6.png)

**Comment by nprail** [comment]
@iborschca Ah yes, I believe only the Chipper 2x supports Bluetooth proximity. 

Are you changing that in the native Swift code? 

You can use this in JS instead:
```typescript
terminal
  .discoverReaders({
    simulated: false,
    discoveryMethod: DiscoveryMethod.BluetoothScan
  })

```

**Comment by iborschca** [comment]
> ```ts
> DiscoveryMethod.BluetoothScan
> ```

yes this works like a charm as well

**Comment by nprail** [comment]
@iborschca no problem!
