### ISSUE TITLE
No cached version of com.stripe:stripeterminal:2.6.0 available for offline mode.

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#88]
**Describe the bug**
When generating a signed bundle / apk in Android studio we now receive the following error: "No cached version of com.stripe:stripeterminal:2.6.0 available for offline mode."

This also happens with 2.5.2.

**To Reproduce**
Install latest plugin version and attempt to build signed bundle / apk

**Expected behavior**
For the project to build successfully in Android Studio

**Desktop (please complete the following information):**

- OS: macOS Big Sur v11.6
- Version 2.1.0-beta.2

**Additional context**
this error also happened with capacitor-stripe-terminal v2.0.0

**Comment by kyleabens** [comment]
I'm now getting the following errors: 
<img width="483" alt="Screen Shot 2022-02-06 at 3 08 27 PM" src="https://user-images.githubusercontent.com/25699262/152699445-1d554e26-d595-42fe-a96c-eb71b48fcc41.png">
<img width="344" alt="Screen Shot 2022-02-06 at 3 08 38 PM" src="https://user-images.githubusercontent.com/25699262/152699447-2708aa3e-7501-4e9d-8401-99770e5bb818.png">

**Comment by kyleabens** [comment]
Turns out this was due to Android Studio being out of date.

**Comment by kyleabens** [comment]
After upgrading this plugin to 2.1.0-beta.3 I get the same error where it's not recognizing BLUETOOTH_CONNECT and BLUETOOTH_SCAN.  I have the latest version of Android Studio and Gradle so I'm not sure how to resolve this.  Any ideas?

**Comment by kyleabens** [comment]
I'll open a new issue on this

**Comment by nprail** [comment]
What's your Android SDK versions?

**Comment by kyleabens** [comment]
@nprail I opened a new issue by the way (#91) so we can pick up the convo over there but I'm currently using 

```
compileSdkVersion 29
minSdkVersion 21
targetSdkVersion 30
```

I did try switching compileSdkVersion and targetSdkVersion to 31 and that didn't make a difference.
