### ISSUE TITLE
batteryLevel is always null in v2.1.0-beta.3

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#90]
**Describe the bug**
the batteryLevel on the reader object is always null in v2.1.0-beta.3

**To Reproduce**
install v2.1.0-beta.3 and discover card readers and look at the reader object for any bluetooth device found

**Expected behavior**
batteryLevel should contain an actual value on reader object just like v2.0.0

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Comment by nprail** [comment]
@kyleabens Are you seeing this only during discovery or always? If it's just during discovery, what discovery method are you using?

**Comment by kyleabens** [comment]
@nprail I'm using the new `both` discovery method.

**Comment by nprail** [comment]
@kyleabens were you using `BluetoothProximity` before?

`Both` uses the `Internet` and `BluetoothScan` methods under the hood. If I remember correctly, `BluetoothScan` does not show battery level during discovery.

**Comment by nprail** [comment]
Closing this since its been dormant for awhile. Re-open if it is still an issue.
