### ISSUE TITLE
get last4 digits of credit card as a result of collectPaymentMethod()

### ISSUE THREAD

**Issue by iborschca** [eventOneHQ/capacitor-stripe-terminal#92]
I am trying to get details of user input, in particular - credit card. I want to implement authentication via credit card tap.
Having wisepad 3. Using this [documentation](https://stripe.com/docs/terminal/features/saving-cards/save-cards-directly?terminal-sdk-platform=ios#collect-payment-method) 
1. It looks like collectPaymentMethod() returns not all details should return [generated_card](https://stripe.com/docs/api/payment_methods/object#payment_method_object-card-last4)
2. It looks like collectPaymentMethod() does not accept customerConsentCollected attribute.

Here is output of the collectPaymentMethod() 
![image](https://user-images.githubusercontent.com/97372700/157172533-996d1d62-59f2-4035-b5b8-f49c8af96060.png)
![image](https://user-images.githubusercontent.com/97372700/157172585-bf911284-6f37-4ed0-94c0-67597d212c5e.png)

**Comment by nprail** [comment]
`PaymentIntent.paymentMethod` was added in [3.0.0-beta.3](https://github.com/eventOneHQ/capacitor-stripe-terminal/releases/tag/v3.0.0-beta.3). Note that it is only available when you pass set `updatePaymentIntent` to true on `collectPaymentMethod`. Also, at the moment, the `paymentMethod` object's properties are camal
