### ISSUE TITLE
Location services must be enabled to use Terminal

### ISSUE THREAD

**Issue by mandray** [eventOneHQ/capacitor-stripe-terminal#93]
- Platform: Android
- Capacitor: 3.4.3
- Ionic: 6.0.0

First, thank you so much for this library, I would have been lost without it.

I'm trying to use it though and even though I'm prompting for permissions and making sure they're granted before initializing Stripe it still says `"Location services must be enabled to use Terminal"` when initializing.

I even checked in settings to make sure the Location permission is enabled and it definitely was.

Any help would be greatly appreciated. 

Here is my code:

```js
const loadStripe = async () => {
    if (Capacitor.getPlatform() === 'android') {
        let response = await StripeTerminalPlugin.checkPermissions();

        if (response.location === 'prompt') {
            response = await StripeTerminalPlugin.requestPermissions();

            if (response.location !== 'granted') {
                throw new Error('Location permission is required.');
            }
        }
    }

    const terminal = await StripeTerminalPlugin.create({
        fetchConnectionToken,
        onUnexpectedReaderDisconnect: async () => {
            console.log('onUnexpectedReaderDisconnect');
        },
    });
};

const fetchConnectionToken = async () => {
    const response = await fetch('http://localhost:5690/connection_token', { method: 'POST' });
    const data = await response.json();
    return data.secret;
};
```

**Comment by nprail** [comment]
What platform and device are you using to test with? Does the device actually have GPS?

**Comment by mandray** [comment]
> What platform and device are you using to test with? Does the device actually have GPS?

I'm using Android with a Galaxy S6 Lite.

Yes, it has GPS, i'm sorry for taking time out of your beautiful day. You made me check the google maps to make sure and it said location was off for the entire device. So even though my example app had the permission granted it wasn't enough

**Comment by mandray** [comment]
Also @nprail thank you for doing Stripes job. They should really pay you. If there's anyway i can send you a tip with bitcoin or something please let us know. You've saved me weeks of work
