### ISSUE TITLE
How to cancel payment intent

### ISSUE THREAD

**Issue by iborschca** [eventOneHQ/capacitor-stripe-terminal#94]
After I created a payment intent on the server side and retrieved it on the client side my terminal bbpos wisepad 3 displays invitation to pay the amount. Let's say client changed his mind and wants to pay cash. Is it possible to cancel it before actual payment collection?

**Comment by nprail** [comment]
You can use [`cancelCollectPaymentMethod`](https://oss.eventone.page/capacitor-stripe-terminal/classes/StripeTerminalPlugin.html#cancelCollectPaymentMethod) to cancel the collection on the reader. On the server side, you can cancel the payment intent as well to keep records clean. 

https://stripe.com/docs/api/payment_intents/cancel
